export default {
  id: "bedrock",
  priority: 35,
  alias: "bedrock",
  aliases: ["aws-bedrock"],
  display: {
    name: "AWS Bedrock",
    icon: "cloud",
    color: "#FF9900",
    textIcon: "BR",
    website: "https://aws.amazon.com/bedrock/",
    notice: {
      text: "Connect Anthropic Claude on Bedrock with an AWS access key ID, secret access key, and region.",
      apiKeyUrl: "https://console.aws.amazon.com/iam/home#/security_credentials",
    },
  },
  category: "apikey",
  authType: "apikey",
  // Region/account catalogs are discovered at runtime and are not bounded by
  // this offline fallback list.
  passthroughModels: true,
  hasProviderSpecificData: true,
  regions: [
    { id: "us-east-1", label: "US East (N. Virginia)" },
    { id: "us-east-2", label: "US East (Ohio)" },
    { id: "us-west-2", label: "US West (Oregon)" },
    { id: "eu-west-1", label: "Europe (Ireland)" },
    { id: "eu-west-3", label: "Europe (Paris)" },
    { id: "eu-central-1", label: "Europe (Frankfurt)" },
    { id: "ap-southeast-1", label: "Asia Pacific (Singapore)" },
    { id: "ap-southeast-2", label: "Asia Pacific (Sydney)" },
    { id: "ap-northeast-1", label: "Asia Pacific (Tokyo)" },
  ],
  defaultRegion: "us-east-1",
  transport: {
    baseUrl: "",
    format: "claude",
    headers: {},
  },
  models: [
    { id: "us.anthropic.claude-opus-4-20250514-v1:0", name: "Claude Opus 4 (US cross-region)" },
    { id: "us.anthropic.claude-sonnet-4-20250514-v1:0", name: "Claude Sonnet 4 (US cross-region)" },
    { id: "eu.anthropic.claude-sonnet-4-20250514-v1:0", name: "Claude Sonnet 4 (EU cross-region)" },
    { id: "apac.anthropic.claude-sonnet-4-20250514-v1:0", name: "Claude Sonnet 4 (APAC cross-region)" },
    { id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0", name: "Claude 3.7 Sonnet (US cross-region)" },
    { id: "anthropic.claude-3-5-sonnet-20241022-v2:0", name: "Claude 3.5 Sonnet v2" },
    { id: "anthropic.claude-3-5-sonnet-20240620-v1:0", name: "Claude 3.5 Sonnet v1" },
    { id: "anthropic.claude-3-5-haiku-20241022-v1:0", name: "Claude 3.5 Haiku" },
    { id: "anthropic.claude-3-opus-20240229-v1:0", name: "Claude 3 Opus" },
    { id: "anthropic.claude-3-sonnet-20240229-v1:0", name: "Claude 3 Sonnet" },
    { id: "anthropic.claude-3-haiku-20240307-v1:0", name: "Claude 3 Haiku" },
  ],
  serviceKinds: ["llm", "imageToText"],
};
