// Adapted from OmniRoute (https://github.com/diegosouzapw/OmniRoute, MIT License,
// Copyright (c) 2026 diegosouzapw). See THIRD_PARTY_NOTICES.md.
export default {
  id: "huggingchat",
  priority: 200,
  hasFree: true,
  alias: "huggingchat",
  display: {
    name: "Huggingchat",
    icon: "bolt",
    color: "#be3798",
    textIcon: "HU",
    notice: {
      text: "Free tier: 24 free models (monthly free allowance, ~1M tokens/mo).",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://huggingface.co/chat/conversation",
    validateUrl: "https://huggingface.co/chat/conversation",
  },
  models: [
    { id: "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT", name: "ERNIE 4.5 VL 424B A47B Base PT", supportsVision: true },
    { id: "CohereLabs/c4ai-command-r7b-12-2024", name: "Command R7B 12-2024", toolCalling: true },
    { id: "CohereLabs/command-a-reasoning-08-2025", name: "Command A Reasoning 08-2025", toolCalling: true },
    { id: "CohereLabs/command-a-vision-07-2025", name: "Command A Vision 07-2025", supportsVision: true },
    { id: "deepseek-ai/DeepSeek-V4-Pro", name: "DeepSeek V4 Pro", toolCalling: true, supportsReasoning: true },
    { id: "deepseek-ai/DeepSeek-V4-Flash", name: "DeepSeek V4 Flash", toolCalling: true },
    { id: "google/gemma-4-31B-it", name: "Gemma 4 31B", toolCalling: true, supportsVision: true },
    { id: "google/gemma-4-26B-A4B-it", name: "Gemma 4 26B A4B", toolCalling: true, supportsVision: true },
    { id: "inclusionAI/Ling-2.6-1T", name: "Ling 2.6 1T", toolCalling: true },
    { id: "meta-llama/Llama-4-Scout-17B-16E-Instruct", name: "Llama 4 Scout 17B 16E Instruct", toolCalling: true, supportsVision: true },
    { id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", name: "Llama 4 Maverick 17B 128E Instruct FP8", supportsVision: true },
    { id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3", toolCalling: true, supportsVision: true, supportsReasoning: true },
    { id: "moonshotai/Kimi-K2.7-Code", name: "Kimi K2.7 Code", toolCalling: true, supportsVision: true, supportsReasoning: true },
    { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6", toolCalling: true, supportsVision: true },
    { id: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4", name: "NVIDIA Nemotron 3 Ultra 550B A55B NVFP4", toolCalling: true, supportsReasoning: true },
    { id: "openai/gpt-oss-120b", name: "GPT-OSS 120B", toolCalling: true, supportsReasoning: true },
    { id: "openai/gpt-oss-20b", name: "GPT-OSS 20B", toolCalling: true, supportsReasoning: true },
    { id: "Qwen/Qwen3.5-122B-A10B", name: "Qwen3.5 122B A10B", toolCalling: true, supportsVision: true },
    { id: "Qwen/Qwen3.5-397B-A17B", name: "Qwen3.5 397B A17B", toolCalling: true, supportsVision: true },
    { id: "Qwen/Qwen3.6-27B", name: "Qwen3.6 27B", toolCalling: true, supportsVision: true },
    { id: "Qwen/Qwen3.6-35B-A3B", name: "Qwen3.6 35B A3B", toolCalling: true, supportsVision: true },
    { id: "stepfun-ai/Step-3.7-Flash", name: "Step 3.7 Flash", toolCalling: true, supportsVision: true },
    { id: "XiaomiMiMo/MiMo-V2.5-Pro", name: "MiMo V2.5 Pro", toolCalling: true },
    { id: "zai-org/GLM-5.2", name: "GLM 5.2", toolCalling: true, supportsReasoning: true }
  ],
  passthroughModels: false,
};
